name: cortai
description: Agendamento para cabeleireiros

version: 0.0.1+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  badges: ^1.1.1
  carousel_slider: 2.2.1
  cloud_firestore: 0.13.7
  cupertino_icons: ^0.1.2
  custom_radio_button: ^0.0.3
  email_validator: ^1.0.4
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  flushbar: 1.10.4
  flutter_auth_buttons: ^0.8.0
  flutter_google_places: ^0.2.5
  flutter_icons: ^1.0.0+1
  flutter_launcher_icons: ^0.7.5
  flutter_masked_text: ^0.8.0
  flutter_mobx: ^1.1.0+1
  flutter_rating_bar: ^3.0.1+1
  geocoder: ^0.2.1
  geolocator: ^5.3.2+2
  getflutter: ^1.0.11
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.5.1
  http: ^0.12.1
  image_picker: ^0.6.5+2
  intl: ^0.16.0
  maps_launcher: ^1.2.1
  mobx: ^1.2.1+1
  password_strength: ^0.1.2
  permission_handler: 5.0.1+1
  photo_view: ^0.9.2
  rxdart: ^0.24.1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.7+3
  shimmer: ^1.1.1
  splashscreen: ^1.2.0
  url_launcher: ^5.4.10
  webview_flutter: ^0.3.22+1


flutter_icons:
  android: true
  ios: true
  adaptive_icon_foreground: true
  image_path: "assets/icons/icon_white.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf


