name: agendacabelo
description: Agendamento para cabeleireiros

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.1.0
  badges: ^1.1.1
  carousel_slider: ^2.0.0
  cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.2
  email_validator: ^1.0.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.0.6
  flushbar: 1.10.2
  flutter_auth_buttons: ^0.8.0
  flutter_icons: ^1.0.0+1
  flutter_masked_text: ^0.8.0
  flutter_rating_bar: ^3.0.1+1
  geocoder: ^0.2.1
  geolocator: ^5.1.4+2
  google_maps_flutter: ^0.5.27+3
  google_sign_in: ^4.4.1
  image_picker: ^0.6.5+2
  intl: ^0.16.0
  permission_handler: ^5.0.0+hotfix.6
  scoped_model: ^1.0.1
  url_launcher: ^5.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf


