name: cortai
description: Agendamento para cabeleireiros

version: 1.0.4+104

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  badges: ^2.0.0-nullsafety.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  email_validator: ^2.0.1
  another_flushbar: ^1.10.17
  flutter_google_places: ^0.3.0
  fluttericon: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  extended_masked_text: ^2.1.0
  flutter_mobx: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^4.1.0
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.0.2
  http: ^0.13.1
  image_picker: ^0.7.4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  maps_launcher: ^2.0.0
  mobx: ^2.0.1
  onesignal_flutter: ^3.0.0-beta2
  password_strength: ^0.2.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.3
  photo_view: ^0.11.1
  progress_indicators: ^1.0.0
  rxdart: ^0.26.0
  scoped_model: ^2.0.0-nullsafety.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  social_share: ^2.1.1
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  flutter_geocoder: ^0.2.2-nullsafety
  encrypt: ^5.0.0
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  pusher_client: ^1.1.3


flutter_icons:
  android: true
  ios: true
  adaptive_icon_foreground: true
  image_path: "assets/icons/icon_white.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.12.2
  json_serializable: ^4.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf


