name: cortai
description: Agendamento para cabeleireiros

version: 1.0.4+104

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  badges: ^1.1.4
  cached_network_image: ^2.4.1
  carousel_slider: 2.3.1
  cupertino_icons: ^1.0.0
  custom_radio_button: ^0.0.3
  dio: ^3.0.10
  email_validator: ^1.0.6
  flushbar: 1.10.4
  flutter_auth_buttons: 0.10.0
  flutter_bcrypt: ^1.0.5
  flutter_google_places: ^0.2.6
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  flutter_masked_text: ^0.8.0
  flutter_mobx: ^1.1.0+2
  flutter_rating_bar: ^3.2.0+1
  flutter_secure_storage: ^3.3.5
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  geolocator: ^6.1.9
  getflutter: ^1.1.3
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.6
  http: ^0.12.2
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  maps_launcher: ^1.2.2+2
  mobx: ^1.2.1+4
  onesignal_flutter: ^2.6.1
  password_strength: ^0.1.2
  permission_handler: 5.0.1+1
  photo_view: ^0.10.3
  pusher_websocket_flutter: ^0.2.0
  rxdart: ^0.24.1
  scoped_model: ^1.1.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  splashscreen: ^1.3.5
  url_launcher: ^5.4.10
  webview_flutter: ^1.0.7
  sizer: ^1.1.8


flutter_icons:
  android: true
  ios: true
  adaptive_icon_foreground: true
  image_path: "assets/icons/icon_white.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf


